hms/urls.py
from django.contrib import admin
from django.urls import path
from selection import views
from django.conf.urls import include, url
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('selection.urls', 'selection'), namespace='selection')),
    url(r'^guest/', include('guest.urls', namespace='guest')),
    path('', views.start, name='start'),
    path('hms/', views.home, name='register'),
    path('reg_form/', views.register, name='reg_form'),
    path('login/', views.user_login, name='login'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('warden_login/', views.warden_login, name='warden_login'),
    path('warden_login/leave', views.leave_admin, name='leave_admin'),
    path('warden_login/student_leaves/<int:std_id>/', views.student_leaves, name='student_leaves'),
    path('warden_login/leave_confirm/<int:lv_id>/', views.leave_confirm, name='leave_confirm'),
    path('warden_login/leave_reject/<int:lv_id>/', views.leave_reject, name='leave_reject'),
    path('warden_login/empty/', views.empty_rooms, name='empty_rooms'),
    path('warden_login/present_leaves/', views.present_leaves, name='present_leaves'),
    path('warden_login/mess_rebate/', views.mess_rebate, name='mess_rebate'),
    path('warden_login/guest_requests/', views.guest_requests, name='guest_requests'),
    path('warden_login/bookings/<int:b_id>/', views.bookings, name='bookings'),
    path('warden_login/confirm/<int:res_id>/', views.guest_accept, name='guest_accept'),
    path('warden_login/cancel/<int:res_id>/', views.guest_reject, name='guest_reject'),
    path('warden_profile/', views.warden_profile, name='warden_profile'),
    path('warden_dues/', views.warden_dues, name='warden_dues'),
    path('warden_add_due/', views.warden_add_due, name='warden_add_due'),
    path('warden_remove_due/', views.warden_remove_due, name='warden_remove_due'),
    path('hostels/', views.hostels, name='hostel_all'),
    path('hostels/<slug:hostel_name>/', views.hostel_detail_view, name='hostel'),
    path('login/edit/', views.edit, name='edit'),
    path('login/select/', views.select, name='select'),
    path('login/repair/', views.repair, name='repair'),
    path('logout/', views.logout_view, name='logout'),
    path('reg_form/login/edit/', views.edit, name='update'),
    path('BH5_GroundFloor/', views.BH5_GroundFloor, name='BH5_GroundFloor'),
    path('BH5_Floor1/', views.BH5_Floor1, name='BH5_Floor1'),
    path('BH5_Floor2/', views.BH5_Floor2, name='BH5_Floor2'),
    path('BH5_Floor3/', views.BH5_Floor3, name='BH5_Floor3'),
    path('BH5_Floor4/', views.BH5_Floor4, name='BH5_Floor4'),
    path('BH5_Floor5/', views.BH5_Floor5, name='BH5_Floor5'),
    path('BH5_Floor6/', views.BH5_Floor6, name='BH5_Floor6'),
    path('login/leave', views.user_leave, name='leave_status'),
    
]

selection/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [

]

selection/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User

class User(AbstractUser):
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('student', 'Student'),
        ('warden', 'Warden'),
        ('guest', 'Guest'),
    )
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, default='student')
    is_warden = models.BooleanField(default=False)



class Student(models.Model):
    user = models.OneToOneField(
        User,
        default=None,
        null=True,
        on_delete=models.CASCADE
        )
    gender_choices = [('N','None'),('M', 'Male'), ('F', 'Female')]
    student_name = models.CharField(max_length=200, null=True)
    father_name = models.CharField(max_length=200, null=True)
    enrollment_no = models.CharField(max_length=10, unique=True, null=True)
    course = models.ForeignKey(
        'Course',
        null=True,
        default=None,
        on_delete=models.CASCADE)
    dob = models.DateField(
        max_length=10,
        help_text="format : YYYY-MM-DD",
        null=True)
    gender = models.CharField(
        choices=gender_choices,
        max_length=1,
        default='N',null=True)
    room = models.OneToOneField(
        'Room',
        blank=True,
        on_delete= models.SET_NULL,
        null=True)
    room_allotted = models.BooleanField(default=False)
    no_dues = models.BooleanField(default=True)

    def __str__(self):
        return str(self.enrollment_no)

    def delete(self, *args, **kwargs):
        room_del = Room.objects.filter(student__room=self.room)
        print('pppppppppppppppppppppppppppppppppppppppp')
        for s in room_del:
            s.vacant = True
            s.save()
            print('***********')
        super(Student, self).delete(*args, **kwargs)


class Room(models.Model):
    room_choice = [('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('P', 'Reserved for Research Scholars'),('B', 'Both Single and Double Occupancy')]
    no = models.CharField(max_length=5)
    name = models.CharField(max_length=10)
    room_type = models.CharField(choices=room_choice, max_length=1, default=None)
    vacant = models.BooleanField(default=False)
    hostel = models.ForeignKey('Hostel', on_delete=models.CASCADE)
    repair = models.CharField(max_length=100, blank=True)


    def __str__(self):
        return '%s %s' %(self.name, self.hostel)

    def delete(self, *args, **kwargs):
        stud = Student.objects.filter(room=self)
        print('pppppppppppppppppppppppppppppppppppppppp')
        for s in stud:
            s.room_allotted = False
            s.save()
            print('***********')
        super(Room, self).delete(*args, **kwargs)


class Hostel(models.Model):
    name = models.CharField(max_length=5)
    gender_choices = [('M', 'Male'), ('F', 'Female')]
    gender = models.CharField(
        choices=gender_choices,
        max_length=1,
        default=None,
        null=True)
    course = models.ManyToManyField('Course', default=None, blank=True)
    caretaker = models.CharField(max_length=100, blank=True)


    def __str__(self):
        return self.name


class Course(models.Model):
    # if a student has enrollment number iit2017001 then the course code is iit2017
    code = models.CharField(max_length=100, default=None)
    room_choice = [('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('P', 'Reserved for Research Scholars'), ('B', 'Both Single and Double Occupancy')]
    room_type = models.CharField(choices=room_choice, max_length=1, default='D')

    def __str__(self):
        return self.code


class Warden(models.Model):
    user = models.OneToOneField(
        User,
        default=None,
        null=True,
        on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    hostel = models.ForeignKey('Hostel',default=None,null=True,
                               on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.user.is_warden is False:  # Set default reference
            self.user.is_warden = True
            self.user.save()
        super(Warden, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.user.is_warden = False
        self.user.save()
        print('pppppppppppppppppppppppppppppppppppppppp')

        super(Warden, self).delete(*args, **kwargs)


class Leave(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    reason = models.CharField(max_length=100,blank = False)
    accept = models.BooleanField(default=False)
    reject = models.BooleanField(default=False)
    confirm_time = models.DateTimeField(auto_now_add=True)

selection/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib import messages
from django.http import HttpResponse, Http404
from selection.models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime,calendar
from guest.models  import Room as Guest_Room,Reservation,Guest
from django.core.exceptions import ObjectDoesNotExist
from .models import Student

def home(request):
    if request.user.is_authenticated and request.user.student:
        return redirect('student_profile')
    return render(request, 'home.html')


def start(request):
    return render(request, 'start.html')

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()

            role = form.cleaned_data['role']

            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password1'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Registration successful! You are now logged in.')

                    if role == 'student':
                        return redirect('student_profile')
                    elif role == 'warden':
                        return redirect('warden_profile')
                    elif role == 'guest':
                        return redirect('empty_rooms')
                    elif role == 'admin':
                        return redirect('start')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = UserForm()

    args = {'form': form}
    return render(request, 'reg_form.html', args)

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'You have been successfully logged in.')

                    if user.is_warden:
                        return redirect('warden_profile')
                    else:
                        return redirect('student_profile')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

def warden_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'])
            if user is not None:
                if user.is_warden:
                    if user.is_active:
                        login(request, user)
                        messages.success(request, 'You have been successfully logged in.')
                        return redirect('warden_profile')
                    else:
                        return HttpResponse('Disabled account')
                else:
                    return HttpResponse('Invalid login')
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

@login_required
def warden_profile(request):
    user = request.user
    if user is not None:
        if not user.is_warden:
            return HttpResponse('Invalid Login')
        elif user.is_active:
            login(request, user)
            room_list = request.user.warden.hostel.room_set.all().order_by('no')
            context = {'rooms': room_list}
            return render(request, 'warden.html', context)
        else:
            return HttpResponse('Disabled account')
    else:
        return HttpResponse('Login to proceed')
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Student

@login_required
def student_profile(request):
    try:
        student = request.user.student
        context = {'student': student}
        return render(request, 'profile.html', context)
    except ObjectDoesNotExist:
        raise Http404("Student profile does not exist")




@login_required
def edit(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, instance=request.user.student)
        if form.is_valid():
            form.save()
            student = request.user.student
            leaves = Leave.objects.filter(student=request.user.student)
            return render(request, 'profile.html', {'student': student, 'leaves': leaves})
        else:
            form = RegistrationForm()
            return render(request, 'edit.html', {'form': form})
    else:
        form = RegistrationForm(instance=request.user.student)
        return render(request, 'edit.html', {'form': form})


@login_required
def select(request):

    if request.method == 'POST':
        if request.user.student.room:
            room_id_old = request.user.student.room_id

        if not request.user.student.no_dues:
            return HttpResponse('You have dues. Please contact your Hostel Caretaker or Warden')
        form = SelectionForm(request.POST, instance=request.user.student)
        if form.is_valid():
            if request.user.student.room_id:
                # stud = form.save(commit=False)
                # print(request.user.student.room_id, stud.room_id)
                request.user.student.room_allotted = True
                r_id_after = request.user.student.room_id
                room = Room.objects.get(id=r_id_after)
                room.vacant = False
                room.save()
                try:
                    room = Room.objects.get(id=room_id_old)
                    room.vacant = True
                    room.save()
                except BaseException:
                    pass
            else:
                request.user.student.room_allotted = False
                try:
                    room = Room.objects.get(id=room_id_old)
                    room.vacant = True
                    room.save()
                except BaseException:
                    pass
            student  = form.save()
            print(student.room_id)
            student = request.user.student
            leaves = Leave.objects.filter(student=request.user.student)
            return render(request, 'profile.html', {'student': student, 'leaves': leaves})
    else:
        if not request.user.student.no_dues:
            return HttpResponse('You have dues. Please contact your Hostel Caretaker or Warden')
        form = SelectionForm(instance=request.user.student)
        student_gender = request.user.student.gender
        student_course = request.user.student.course
        if student_course is None:
            return HttpResponse('No Course Selected <br> '
                                '<h3><a href = \'..\edit\' style = "text-align: center; color: Red ;"> Update Profile </a> </h3> ')
        student_room_type = request.user.student.course.room_type
        hostel = Hostel.objects.filter(
            gender=student_gender, course=student_course).order_by('name')
        print(student_gender, student_course, student_room_type)
        print(hostel)
        x = Room.objects.none()
        if student_room_type == 'B':
            print(student_room_type)
            for i in range(len(hostel)):
                h_id = hostel[i].id
            x = Room.objects.filter(
                hostel__id=hostel, room_type=['S','D'], vacant=True).order_by('no')
        else:
            for i in range(len(hostel)):
                h_id = hostel[i].id
            x = Room.objects.filter(
                hostel_id__in=hostel, room_type=student_room_type, vacant=True).order_by('hostel_id','no')
            print(x)
        form.fields["room"].queryset = x
        print('x',x)
        return render(request, 'select_room.html', {'form': form})

@login_required
def repair(request):

    if request.method == 'POST':
        form = RepairForm(request.POST)
        if form.is_valid() & request.user.student.room_allotted:

            rep = form.cleaned_data['repair']
            room = request.user.student.room
            room.repair = rep
            room.save()
            return HttpResponse('<h3>Complaint Registered</h3> <br> <a href = \'../../student_profile\''
                                ' style = "text-align: center; color: Red ;"> Go Back to Profile </a>')
        elif not request.user.student.room_allotted:
            return HttpResponse('<h3>First Select a Room </h3> <br> <a href = \'../select\''
                                ' style = "text-align: center; color: Red ;"> SELECT ROOM </a> ')

        else:
            form = RepairForm()
            room = request.user.student.room
            return render(request, 'repair_form.html', {'form': form, 'room': room})
    else:
        if not request.user.student.room_allotted:
            return HttpResponse('<h3>First Select a Room </h3> <br> <a href = \'../select\''
                                ' style = "text-align: center; color: Red ;"> SELECT ROOM </a> ')
        else:
            form = RepairForm()
            room = request.user.student.room
            return render(request, 'repair_form.html', {'form': form,'room': room})





@login_required
def warden_dues(request):
    user = request.user
    if user is not None:
        if not user.is_warden:

selection/templates/BH5_Floor3.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class="nav" style="background-color: #638acc;">
  <div class="nav-header">
    <div class="nav-title">
      <a href="{% url 'BH5_Floor4' %}">Hostels</a>
    </div>
  </div>
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  <input type="checkbox" id="nav-check">
  <div class="dropdown">
    <button class="dropbtn">BH5</button>
    <div class="dropdown-content" style="right: 20px;">
      <a href="{% url 'BH5_GroundFloor' %}">Ground Floor</a>
      <a href="{% url 'BH5_Floor1' %}">Floor 1</a>
      <a href="{% url 'BH5_Floor2' %}">Floor 2</a>
      <a href="{% url 'BH5_Floor3' %}">Floor 3</a>
      <a href="{% url 'BH5_Floor4' %}">Floor 4</a>
      <a href="{% url 'BH5_Floor5' %}">Floor 5</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">BH4</button>
    <div class="dropdown-content">
      <a href="#">Floor 1</a>
      <a href="#">Floor 2</a>
      <a href="#">Floor 3</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">BH3</button>
    <div class="dropdown-content">
      <a href="#">Floor 1</a>
      <a href="#">Floor 2</a>
      <a href="#">Floor 3</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">BH2</button>
    <div class="dropdown-content">
      <a href="#">Floor 1</a>
      <a href="#">Floor 2</a>
      <a href="#">Floor 3</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">BH1</button>
    <div class="dropdown-content">
      <a href="#">Floor 1</a>
      <a href="#">Floor 2</a>
      <a href="#">Floor 3</a>
    </div>
  </div>
</div>
<div class="row">
  <div>
    <div class="grid">
      <table class="table1">
        <tr>
          <td colspan="33" id="walk">  </td>
        </tr>
        <tr>
          <td colspan="33" id="walk">  </td>
        </tr>
        <tr>
          <td id="walk">  </td>
          <td id="walk">  </td>
          <td id="walk">  </td>
          <td colspan="2" id="walk">  </td>
          <td><div id="seat"></div></td>
          <td><div id="seat"></div></td>
          <td colspan="10" id="walk"></td>
          </tr>
          <tr>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td colspan="2" id="walk">  </td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td><div id="seat"></div></td>
            <td><div id="seat"></div></td>
            <td id="walk">  </td>
            <td id="walk">  </td>
            <td id="walk">  </td>
          </tr>
          <tr>
            <td colspan="33" id="walk">  </td>
          </tr>
          <tr>
            <td colspan="33" id="walk">  </td>
          </tr>
        </table>
      </div>
    </div>
    {% endblock %}
    

selection/templates/add_due.html
{% extends 'base.html' %}

{% block content %}
<div class="wrap">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields">{{ form.as_p }}</div>
      <input class="button-custom" type="submit" value="ADD DUE">
    </form>
  </div>
{% endblock content %}


{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'warden_dues' %}">
        Dues
    </a>
    <!--<a href="{% url 'warden_add_due' %}">-->
        <!--Add Due-->
    <!--</a>-->
    <a href="{% url 'warden_remove_due' %}">
        Remove Due
    </a>
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

selection/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Student Management System | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static 'tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static "icheck-bootstrap/icheck-bootstrap.min.css" %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static "jqvmap/jqvmap.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'  %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static "overlayScrollbars/css/OverlayScrollbars.min.css" %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static "daterangepicker/daterangepicker.css" %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static "summernote/summernote-bs4.css" %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'selection/style.css' %}">
</head>

<body>

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'student_profile' %}" class="brand-link">
        <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Open university</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{% url 'student_profile' %}" class="d-block">{{ user.first_name }} {{ user.last_name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->

                <li class="nav-item">
                    <a href="{% url 'register' %}" class="nav-link">
                        <i class="nav-icon fas fa-tools"></i>
                        <p>Register</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'repair' %}" class="nav-link">
                        <i class="nav-icon fas fa-tools"></i>
                        <p>Repair</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>Logout</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'leave_status' %}" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>Leave Status</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

<div>
    {% block content %}
    {% endblock content %}
</div>

<footer>
    <div class="copyright" align="center">
        2023 © Hostel System Management
    </div>
</footer>

</body>

</html>

selection/templates/empty_rooms.html
{% extends 'base.html' %}

{% block content %}
    {% if rooms %}
        <h2 style="text-align: center; color: red;">Empty Rooms</h2>
        <div class="wrapper">
            <div class="table">
                <div class="row header">
                    <div class="cell">
                        Hostel
                    </div>
                    <div class="cell">
                        Room No
                    </div>
                    <div class="cell">
                        Type
                    </div>
                    <div class="cell">
                        Status
                    </div>
                </div>
                {% for room in rooms %}
                    <div class="row">
                        <div class="cell" data-title="Hostel">
                            {{ room.hostel.name }}
                        </div>
                        <div class="cell" data-title="Room No">
                            {{ room.no }}
                        </div>
                        <div class="cell" data-title="Type">
                            {{ room.room_type }}
                        </div>
                        <div class="cell" {% if room.student %}style="color: green;"{% endif %} data-title="Status">
                            {% if room.student %}Occupied{% else %}Vacant{% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <h2 style="text-align: center; color: red;">No Empty Rooms</h2>
    {% endif %}
{% endblock content %}

{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'leave_admin' %}">
        Leave requests
    </a>
    <a href="{% url 'present_leaves' %}">
        Present Leave
    </a>
    <a href="{% url 'mess_rebate' %}">
        Mess Rebate
    </a>
    <a href="{% url 'guest_requests' %}">
        Guest Room Requests
    </a>
    <!--<a href="{% url 'warden_dues' %}">-->
        <!--Dues-->
    <!--</a>-->
    <!--<a href="{% url 'warden_add_due' %}">-->
        <!--Add Due-->
    <!--</a>-->
    <!--<a href="{% url 'warden_remove_due' %}">-->
        <!--Remove Due-->
    <!--</a>-->
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}

selection/templates/login.html
{% extends 'base.html' %}

{% block content %}
    {% if message %}
        <div class="alert alert-success">{{ message }}</div>
    {% endif %}

    {% if warning %}
        <div class="alert alert-warning">{{ warning }}</div>
    {% endif %}

    {% if not user.is_authenticated %}
        <div class="alert alert-info">Please login to view this page.</div>
    {% else %}
        <div class="wrap">
            <form action="" method="post">
                {% csrf_token %}
                <div class="fields">
                    <label for="id_username">Username</label><br><br>
                    {{ form.username }}
                </div>
                <div class="password">
                    <label for="id_password">Password</label><br><br>
                    {{ form.password }}
                </div>
                <div class="role">
                    <label for="id_role">Role</label><br><br>
                    {% for choice in form.role.field.choices %}
                        <input type="radio" id="{{ choice.0 }}" name="role" value="{{ choice.0 }}" {% if choice.0 == 'student' %}checked{% endif %}>
                        <label for="{{ choice.0 }}">{{ choice.1 }}</label><br>
                    {% endfor %}
                </div>
                <input class="button-custom" type="submit" value="LOGIN">
            </form>
        </div>
    {% endif %}
{% endblock content %}

{% block more_links %}
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'reg_form' %}">Register</a>
{% endblock more_links %}

selection/templates/remove_due.html
{% extends 'base.html' %}

{% block content %}
<div class="wrap">
    <form action="" method="post">
        {% csrf_token %}
      <div class="fields">{{ form.as_p }}</div>
      <input class="button-custom" type="submit" value="REMOVE DUE">
    </form>
  </div>
{% endblock content %}


{% block more_links %}
    <a href="{% url 'warden_profile' %}">
        Profile
    </a>
    <a href="{% url 'warden_dues' %}">
        Dues
    </a>
    <a href="{% url 'warden_add_due' %}">
        Add Due
    </a>
    <a href="{% url 'logout' %}">
        Logout
    </a>
{% endblock more_links %}